// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: plugin.proto

package pluginmanager

import (
	runtime "github.com/VeritasOS/plugin-manager/utils/runtime"
	status "github.com/VeritasOS/plugin-manager/utils/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginAttributes that are supported in a plugin file.
type PluginAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	ExecStart     string                 `protobuf:"bytes,3,opt,name=ExecStart,proto3" json:"ExecStart,omitempty"`
	RequiredBy    []string               `protobuf:"bytes,4,rep,name=RequiredBy,proto3" json:"RequiredBy,omitempty"`
	Requires      []string               `protobuf:"bytes,5,rep,name=Requires,proto3" json:"Requires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginAttributes) Reset() {
	*x = PluginAttributes{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAttributes) ProtoMessage() {}

func (x *PluginAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginAttributes.ProtoReflect.Descriptor instead.
func (*PluginAttributes) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginAttributes) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PluginAttributes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginAttributes) GetExecStart() string {
	if x != nil {
		return x.ExecStart
	}
	return ""
}

func (x *PluginAttributes) GetRequiredBy() []string {
	if x != nil {
		return x.RequiredBy
	}
	return nil
}

func (x *PluginAttributes) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

// Plugins is basically a map of file and its contents.
type Plugins struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Attributes    map[string]*PluginAttributes `protobuf:"bytes,1,rep,name=Attributes,proto3" json:"Attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plugins) Reset() {
	*x = Plugins{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugins) ProtoMessage() {}

func (x *Plugins) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugins.ProtoReflect.Descriptor instead.
func (*Plugins) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Plugins) GetAttributes() map[string]*PluginAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// PluginStatus is the plugin run's info: status, stdouterr.
type PluginStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    *PluginAttributes      `protobuf:"bytes,1,opt,name=Attributes,proto3" json:"Attributes,omitempty"`
	Status        status.Status          `protobuf:"varint,2,opt,name=Status,proto3,enum=status.Status" json:"Status,omitempty"`
	StdOutErr     []string               `protobuf:"bytes,3,rep,name=StdOutErr,proto3" json:"StdOutErr,omitempty"`
	RunTime       *runtime.RunTime       `protobuf:"bytes,4,opt,name=RunTime,proto3" json:"RunTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginStatus) GetAttributes() *PluginAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *PluginStatus) GetStatus() status.Status {
	if x != nil {
		return x.Status
	}
	return status.Status(0)
}

func (x *PluginStatus) GetStdOutErr() []string {
	if x != nil {
		return x.StdOutErr
	}
	return nil
}

func (x *PluginStatus) GetRunTime() *runtime.RunTime {
	if x != nil {
		return x.RunTime
	}
	return nil
}

// PluginTypeStatus is the pm run status of given Type plugin.
type PluginTypeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Plugins       []*PluginStatus        `protobuf:"bytes,2,rep,name=Plugins,proto3" json:"Plugins,omitempty"`
	Status        status.Status          `protobuf:"varint,3,opt,name=Status,proto3,enum=status.Status" json:"Status,omitempty"`
	StdOutErr     string                 `protobuf:"bytes,4,opt,name=StdOutErr,proto3" json:"StdOutErr,omitempty"`
	RunTime       *runtime.RunTime       `protobuf:"bytes,5,opt,name=RunTime,proto3" json:"RunTime,omitempty"` // TODO: Add Percentage to get no. of pending vs. completed run of plugins.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginTypeStatus) Reset() {
	*x = PluginTypeStatus{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginTypeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTypeStatus) ProtoMessage() {}

func (x *PluginTypeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTypeStatus.ProtoReflect.Descriptor instead.
func (*PluginTypeStatus) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PluginTypeStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginTypeStatus) GetPlugins() []*PluginStatus {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *PluginTypeStatus) GetStatus() status.Status {
	if x != nil {
		return x.Status
	}
	return status.Status(0)
}

func (x *PluginTypeStatus) GetStdOutErr() string {
	if x != nil {
		return x.StdOutErr
	}
	return ""
}

func (x *PluginTypeStatus) GetRunTime() *runtime.RunTime {
	if x != nil {
		return x.RunTime
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x06plugin\x1a\rruntime.proto\x1a\fstatus.proto\"\xaa\x01\n" +
	"\x10PluginAttributes\x12\x1a\n" +
	"\bFileName\x18\x01 \x01(\tR\bFileName\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x1c\n" +
	"\tExecStart\x18\x03 \x01(\tR\tExecStart\x12\x1e\n" +
	"\n" +
	"RequiredBy\x18\x04 \x03(\tR\n" +
	"RequiredBy\x12\x1a\n" +
	"\bRequires\x18\x05 \x03(\tR\bRequires\"\xa3\x01\n" +
	"\aPlugins\x12?\n" +
	"\n" +
	"Attributes\x18\x01 \x03(\v2\x1f.plugin.Plugins.AttributesEntryR\n" +
	"Attributes\x1aW\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.plugin.PluginAttributesR\x05value:\x028\x01\"\xba\x01\n" +
	"\fPluginStatus\x128\n" +
	"\n" +
	"Attributes\x18\x01 \x01(\v2\x18.plugin.PluginAttributesR\n" +
	"Attributes\x12&\n" +
	"\x06Status\x18\x02 \x01(\x0e2\x0e.status.StatusR\x06Status\x12\x1c\n" +
	"\tStdOutErr\x18\x03 \x03(\tR\tStdOutErr\x12*\n" +
	"\aRunTime\x18\x04 \x01(\v2\x10.runtime.RunTimeR\aRunTime\"\xc8\x01\n" +
	"\x10PluginTypeStatus\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12.\n" +
	"\aPlugins\x18\x02 \x03(\v2\x14.plugin.PluginStatusR\aPlugins\x12&\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x0e.status.StatusR\x06Status\x12\x1c\n" +
	"\tStdOutErr\x18\x04 \x01(\tR\tStdOutErr\x12*\n" +
	"\aRunTime\x18\x05 \x01(\v2\x10.runtime.RunTimeR\aRunTimeB3Z1github.com/VeritasOS/plugin-manager/pluginmanagerb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_proto_goTypes = []any{
	(*PluginAttributes)(nil), // 0: plugin.PluginAttributes
	(*Plugins)(nil),          // 1: plugin.Plugins
	(*PluginStatus)(nil),     // 2: plugin.PluginStatus
	(*PluginTypeStatus)(nil), // 3: plugin.PluginTypeStatus
	nil,                      // 4: plugin.Plugins.AttributesEntry
	(status.Status)(0),       // 5: status.Status
	(*runtime.RunTime)(nil),  // 6: runtime.RunTime
}
var file_plugin_proto_depIdxs = []int32{
	4, // 0: plugin.Plugins.Attributes:type_name -> plugin.Plugins.AttributesEntry
	0, // 1: plugin.PluginStatus.Attributes:type_name -> plugin.PluginAttributes
	5, // 2: plugin.PluginStatus.Status:type_name -> status.Status
	6, // 3: plugin.PluginStatus.RunTime:type_name -> runtime.RunTime
	2, // 4: plugin.PluginTypeStatus.Plugins:type_name -> plugin.PluginStatus
	5, // 5: plugin.PluginTypeStatus.Status:type_name -> status.Status
	6, // 6: plugin.PluginTypeStatus.RunTime:type_name -> runtime.RunTime
	0, // 7: plugin.Plugins.AttributesEntry.value:type_name -> plugin.PluginAttributes
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
