// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: workflow.proto

package pluginmanager

import (
	runtime "github.com/VeritasOS/plugin-manager/utils/runtime"
	status "github.com/VeritasOS/plugin-manager/utils/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workflow indicates action and rollback plugin types to be run.
type Workflow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActionRollbacks []*ActionRollback      `protobuf:"bytes,1,rep,name=ActionRollbacks,proto3" json:"ActionRollbacks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *Workflow) GetActionRollbacks() []*ActionRollback {
	if x != nil {
		return x.ActionRollbacks
	}
	return nil
}

// ActionRollback basically contains plugin-type info for Action and Rollback.
type ActionRollback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=Action,json=action,proto3" json:"Action,omitempty"`
	Rollback      string                 `protobuf:"bytes,2,opt,name=Rollback,json=rollback,proto3" json:"Rollback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRollback) Reset() {
	*x = ActionRollback{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRollback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRollback) ProtoMessage() {}

func (x *ActionRollback) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRollback.ProtoReflect.Descriptor instead.
func (*ActionRollback) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *ActionRollback) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionRollback) GetRollback() string {
	if x != nil {
		return x.Rollback
	}
	return ""
}

// WorkflowStatus contains status info for Workflow.
type WorkflowStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        []*PluginTypeStatus    `protobuf:"bytes,1,rep,name=Action,proto3" json:"Action,omitempty"`
	Rollback      []*PluginTypeStatus    `protobuf:"bytes,2,rep,name=Rollback,proto3" json:"Rollback,omitempty"`
	Status        status.Status          `protobuf:"varint,3,opt,name=Status,proto3,enum=status.Status" json:"Status,omitempty"`
	StdOutErr     string                 `protobuf:"bytes,4,opt,name=StdOutErr,proto3" json:"StdOutErr,omitempty"`
	RunTime       *runtime.RunTime       `protobuf:"bytes,5,opt,name=RunTime,proto3" json:"RunTime,omitempty"` // TODO: Add Percentage to get no. of pending vs. completed run of plugins.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStatus) Reset() {
	*x = WorkflowStatus{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatus) ProtoMessage() {}

func (x *WorkflowStatus) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatus.ProtoReflect.Descriptor instead.
func (*WorkflowStatus) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowStatus) GetAction() []*PluginTypeStatus {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *WorkflowStatus) GetRollback() []*PluginTypeStatus {
	if x != nil {
		return x.Rollback
	}
	return nil
}

func (x *WorkflowStatus) GetStatus() status.Status {
	if x != nil {
		return x.Status
	}
	return status.Status(0)
}

func (x *WorkflowStatus) GetStdOutErr() string {
	if x != nil {
		return x.StdOutErr
	}
	return ""
}

func (x *WorkflowStatus) GetRunTime() *runtime.RunTime {
	if x != nil {
		return x.RunTime
	}
	return nil
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\bworkflow\x1a\fplugin.proto\x1a\rruntime.proto\x1a\fstatus.proto\"N\n" +
	"\bWorkflow\x12B\n" +
	"\x0fActionRollbacks\x18\x01 \x03(\v2\x18.workflow.ActionRollbackR\x0fActionRollbacks\"D\n" +
	"\x0eActionRollback\x12\x16\n" +
	"\x06Action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bRollback\x18\x02 \x01(\tR\brollback\"\xea\x01\n" +
	"\x0eWorkflowStatus\x120\n" +
	"\x06Action\x18\x01 \x03(\v2\x18.plugin.PluginTypeStatusR\x06Action\x124\n" +
	"\bRollback\x18\x02 \x03(\v2\x18.plugin.PluginTypeStatusR\bRollback\x12&\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x0e.status.StatusR\x06Status\x12\x1c\n" +
	"\tStdOutErr\x18\x04 \x01(\tR\tStdOutErr\x12*\n" +
	"\aRunTime\x18\x05 \x01(\v2\x10.runtime.RunTimeR\aRunTimeB3Z1github.com/VeritasOS/plugin-manager/pluginmanagerb\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workflow_proto_goTypes = []any{
	(*Workflow)(nil),         // 0: workflow.Workflow
	(*ActionRollback)(nil),   // 1: workflow.ActionRollback
	(*WorkflowStatus)(nil),   // 2: workflow.WorkflowStatus
	(*PluginTypeStatus)(nil), // 3: plugin.PluginTypeStatus
	(status.Status)(0),       // 4: status.Status
	(*runtime.RunTime)(nil),  // 5: runtime.RunTime
}
var file_workflow_proto_depIdxs = []int32{
	1, // 0: workflow.Workflow.ActionRollbacks:type_name -> workflow.ActionRollback
	3, // 1: workflow.WorkflowStatus.Action:type_name -> plugin.PluginTypeStatus
	3, // 2: workflow.WorkflowStatus.Rollback:type_name -> plugin.PluginTypeStatus
	4, // 3: workflow.WorkflowStatus.Status:type_name -> status.Status
	5, // 4: workflow.WorkflowStatus.RunTime:type_name -> runtime.RunTime
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	file_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
