---
# Copyright (c) 2024 Veritas Technologies LLC. All rights reserved. IP63-2828-7171-04-15-9
pluginmanager:
  # `library` is the location where plugins directories containing plugins are expected to be present
  library: "../sample/library"
  log dir: "./"
  # `log file` indicates the name of the log file.
  #   The timestamp and '.log' extension would be appended to this name.
  #   I.e., The format of the log file generated would be: "<log file>.<timestamp>.log"
  #   Example: The below value results in following log file: pm.2020-01-13T16:11:58.6006565-08:00.log
  log file: "pm"
  # 'log level' indicates the type (ERROR, WARNING, INFO, DEBUG) of log messages to be logged. Setting a particular log-level say "INFO", logs all messages of that type (i.e., "INFO") as well as the previous messages types (i.e., ERROR and WARNING).
  log level: "DEBUG"
...
