// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: runtime.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunTime contains start, end and duration for capturing execution time.
type RunTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTime) Reset() {
	*x = RunTime{}
	mi := &file_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTime) ProtoMessage() {}

func (x *RunTime) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTime.ProtoReflect.Descriptor instead.
func (*RunTime) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RunTime) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *RunTime) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *RunTime) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_runtime_proto protoreflect.FileDescriptor

const file_runtime_proto_rawDesc = "" +
	"\n" +
	"\rruntime.proto\x12\aruntime\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\aRunTime\x128\n" +
	"\tStartTime\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tStartTime\x124\n" +
	"\aEndTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aEndTime\x125\n" +
	"\bDuration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bDurationB3Z1github.com/VeritasOS/plugin-manager/utils/runtimeb\x06proto3"

var (
	file_runtime_proto_rawDescOnce sync.Once
	file_runtime_proto_rawDescData []byte
)

func file_runtime_proto_rawDescGZIP() []byte {
	file_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)))
	})
	return file_runtime_proto_rawDescData
}

var file_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_runtime_proto_goTypes = []any{
	(*RunTime)(nil),               // 0: runtime.RunTime
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 2: google.protobuf.Duration
}
var file_runtime_proto_depIdxs = []int32{
	1, // 0: runtime.RunTime.StartTime:type_name -> google.protobuf.Timestamp
	1, // 1: runtime.RunTime.EndTime:type_name -> google.protobuf.Timestamp
	2, // 2: runtime.RunTime.Duration:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_runtime_proto_init() }
func file_runtime_proto_init() {
	if File_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_proto_depIdxs,
		MessageInfos:      file_runtime_proto_msgTypes,
	}.Build()
	File_runtime_proto = out.File
	file_runtime_proto_goTypes = nil
	file_runtime_proto_depIdxs = nil
}
